### ISSUE TITLE
The resampling counts in the paper and the code are inconsistent.

### ISSUE THREAD

**Issue by Zian-Xu** [liuxu77/UniTime#11]
Thank you for your excellent work. I've benefited greatly. However, I encountered an issue while reproducing the results from the paper.

In paper's Section B, `TRAINING CONFIGURATIONS`, it states, “The decision to perform oversampling **12 times** on the Illness dataset is based on our empirical assessments.” However, in `execute_list/train_all.csv`, Illness appears **13 times**, which contradicts the paper’s description.

Could you clarify whether the results presented in the paper were obtained by oversampling Illness 12 times or 13 times?

Thank you very much, and I look forward to your prompt reply.

**Comment by liuxu77** [comment]
Hi, the numbers are correct. The illness data should appear once (otherwise it is not training) and be oversampled 12 times.
