### ISSUE TITLE
Question about Time Feature Matrices

### ISSUE THREAD

**Issue by cccccrj** [liuxu77/UniTime#12]
First of all, thank you for your impressive work. I’ve learned a lot from your research and implementation, and I truly appreciate the effort you’ve put into making this available.

While going through the code, I came across the file utils/timefeatures.py, where there is a function that seems to transform timestamps into some form of feature matrix. However, I couldn’t find where this feature matrix is actually utilized in the codebase or mentioned in the paper.

**Question**：Could you please clarify the purpose of these time feature matrices? And where in the codebase are they used?

Looking forward to your insights, and thank you again for your incredible contribution!

**Comment by liuxu77** [comment]
Hi @cccccrj, thanks for asking. These time features are used in the original repo: https://github.com/thuml/Time-Series-Library. In our repo, we actually did not use them.

**Comment by cccccrj** [comment]
**Description:**  
Thank you for your explanation! Additionally, I have a small question regarding positional embeddings.  

The original paper states the following:  
> The input to the proposed Language-TS Transformer is: H=(E||Z)+𝑾𝑝𝑜𝑠. where E||Z represents the concatenation operation, and 𝑾𝑝𝑜𝑠 is the learnable positional embeddings from the pretrained language model.  

Based on this description, after concatenating the temporal embedding (Z) and text embedding (E), a positional embedding (𝑾𝑝𝑜𝑠) should be added.  

However, I couldn't find an explicit implementation of adding positional embeddings in the code. The relevant code snippet is as follows:  
```python
if len(instruct) > 0:
    instruct_ids = self.tokenizer(instruct, return_tensors='pt').input_ids.to(x_inp.device)
    instruct_embed = self.backbone.transformer.wte(instruct_ids).repeat(x_token.shape[0], 1, 1)
    inputs_embeds = torch.cat((instruct_embed, x_token), dim=1)
else:
    inputs_embeds = x_token
x_enc = self.backbone(inputs_embeds=inputs_embeds)
```

**My question is:**  
I didn't see the positional embedding being added in this implementation. Was this part of the design eventually abandoned, or was it simply omitted from the code? If it was abandoned, I’d love to understand the reasoning behind the decision.

**Comment by liuxu77** [comment]
Hi @cccccrj, this part is implemented inside the source code of the transformers library, please refer to: https://github.com/huggingface/transformers/blob/main/src/transformers/models/gpt2/modeling_gpt2.py#L1032

**Comment by cccccrj** [comment]
Thank you for your previous response! Additionally, I noticed that your paper mentions a method introducing channel independence. However, I couldn't locate the corresponding implementation in the model's code definition. Could you kindly point out where this part of the code is implemented?

Thank you once again for sharing! Looking forward to your reply.
