### ISSUE TITLE
About features mode in forecasting performance

### ISSUE THREAD

**Issue by Alsac** [liuxu77/UniTime#7]
![image](https://github.com/liuxu77/UniTime/assets/33149313/1a40e121-3313-4c8d-9a81-869e680d93ce)

Thank you for your excellent work! I just want clearly know if this table is test on 'M' mode or 'MS' mode of features parameter?

**Comment by liuxu77** [comment]
Hi, the feature mode was set to 'M', you can refer to the .conf files in data_configs folder.
