### ISSUE TITLE
experiments

### ISSUE THREAD

**Issue by x1370161679** [liuxu77/UniTime#8]
Hello, may I ask how you adjust the parameters of other models to conduct comparative experiments? Can you share the code?

**Comment by liuxu77** [comment]
Most of the results are from the TimesNet paper, please refer to it.

**Comment by x1370161679** [comment]
> Most of the results are from the TimesNet paper, please refer to it.

Due to the lack of GPU memory, there are only 3090 
 24G, I deleted the Electricity data field, and the other parameters remain the same. But I've been training for a long time, and I still haven't reached the accuracy in your table, and I've also tried to reduce the batch of the Electricity data field to 4, but it still doesn't work, and the MSE is probably 0.01 lower than in the table. Really looking forward to your reply, thank you
