### ISSUE TITLE
Sequence reconstruction

### ISSUE THREAD

**Issue by x1370161679** [liuxu77/UniTime#9]
Hello, I haven't seen the sequence reconstruction part in the code. Is it possible that this part has been removed from the code? The accuracy I've tested is indeed about one percentage point lower than what's mentioned in the paper. I'm looking forward to your answer. Thank you.

**Comment by liuxu77** [comment]
Please refer to the code in engine_forecasting.py file row 40-42.

**Comment by x1370161679** [comment]
> Please refer to the code in engine_forecasting.py file row 40-42.

Thanks for your reply
